### ISSUE TITLE
Doesn't run in macOS

### ISSUE THREAD

**Issue by alidaf** [derkork/openscad-graph-editor#21]
On clicking, message is that app is damaged and can't be opened.

**To Reproduce**
Double click on app

**Desktop (please complete the following information):**
macOS Monterey on iMac (Intel)

**Comment by derkork** [comment]
This is because the app is not signed with the Apple developer program, you will have to manually de-quarantine the app. See [this FAQ entry](https://github.com/derkork/openscad-graph-editor/blob/master/manual/faq.md#i-cannot-open-the-app-on-the-mac-it-says-it-is-damaged) for details on how to do this.
